### PR TITLE
V1.0.0

### PR DESCRIPTION
**Pull request by natashapinto**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_ed_readcount_analysis/1)

### CODE REVIEW

**Review by Graeme-Smith — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_ed_readcount_analysis/1)* status: all files reviewed, 2 unresolved discussions (waiting on @natashapinto)

___
*[src/code.sh, line 56 at r3](https://reviewable.io/reviews/moka-guys/dnanexus_ed_readcount_analysis/1#-MqQ7vh_1_SGLS0LNFOF:-MqQ7vh_1_SGLS0LNFOG:bw2vwa1) ([raw file](https://github.com/moka-guys/dnanexus_ed_readcount_analysis/blob/163d65d839ddea52c2f33a382d9ef492c40da36e/src/code.sh#L56)):*
> ```Shell
> 
> #Get list of all BAMs 
> bam_list=""
> ```

Why do you initialise a empty string which you then redeclare below?
___
*[src/code.sh, line 87 at r3](https://reviewable.io/reviews/moka-guys/dnanexus_ed_readcount_analysis/1#-MqQ8qAm1xiZRkuQ8A6S:-MqQ8qAm1xiZRkuQ8A6T:b-15xitu) ([raw file](https://github.com/moka-guys/dnanexus_ed_readcount_analysis/blob/163d65d839ddea52c2f33a382d9ef492c40da36e/src/code.sh#L87)):*
> ```Shell
> # Run command below to create panel of normals
> #docker run -v /home/dnanexus:/home/dnanexus ${DOCKERIMAGENAME} readCount.R /home/dnanexus/out/exomedepth_output/exomedepth_output/$bedfile_prefix/normals.RData $reference_genome_path $bedfile_path $bam_list
> ```

I assume this section of code is meant to be commented out and you don't need to calculate a panel of normals?

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_ed_readcount_analysis/1)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @Graeme-Smith and @natashapinto)

___
*[src/code.sh, line 87 at r3](https://reviewable.io/reviews/moka-guys/dnanexus_ed_readcount_analysis/1#-MqQ8qAm1xiZRkuQ8A6S:-MsBqZze6kT3TGfB2zH5:b-a6az1b) ([raw file](https://github.com/moka-guys/dnanexus_ed_readcount_analysis/blob/163d65d839ddea52c2f33a382d9ef492c40da36e/src/code.sh#L87)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

I assume this section of code is meant to be commented out and you don't need to calculate a panel of normals?
</blockquote></details>

moved to readme

**Review by Graeme-Smith — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_ed_readcount_analysis/1)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @Graeme-Smith and @natashapinto)

___
*[dxapp.json, line 31 at r5](https://reviewable.io/reviews/moka-guys/dnanexus_ed_readcount_analysis/1#-Ms_qDJF9dXQ6SZxVIZ5:-Ms_qDJF9dXQ6SZxVIZ6:bjxyja9) ([raw file](https://github.com/moka-guys/dnanexus_ed_readcount_analysis/blob/f06f085772821fb82c884467fb591f1959092a59/dxapp.json#L31)):*
> ```JSON
>             }
>         }
>       ],
> ```

I've not used the suggestions tag before, does it auto fill a dropdown box?
___
*[src/code.sh, line 68 at r5](https://reviewable.io/reviews/moka-guys/dnanexus_ed_readcount_analysis/1#-Ms_qeKp2TWVs4qOlBLx:-Ms_qeKq3wE9ZiXbvjf0:b-2slml0) ([raw file](https://github.com/moka-guys/dnanexus_ed_readcount_analysis/blob/f06f085772821fb82c884467fb591f1959092a59/src/code.sh#L68)):*
> ```Shell
> # NB (include full filepath to ensure the output are absolute paths (needed for docker run))
> bam_list="$(ls /home/dnanexus/to_test/*bam | tr '\n' ' ')"
> ```

You don't need to use ls or trim, globbing will return an array of bams at that locate , this code is equivalent to:



_Code snippet:_
```Shell
bam_list=(/home/dnanexus/to_test/*bam)
```

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_ed_readcount_analysis/1)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @Graeme-Smith)

___
*[dxapp.json, line 31 at r5](https://reviewable.io/reviews/moka-guys/dnanexus_ed_readcount_analysis/1#-Ms_qDJF9dXQ6SZxVIZ5:-Msatvpr91duQ1ObH2iY:b1yayuy) ([raw file](https://github.com/moka-guys/dnanexus_ed_readcount_analysis/blob/f06f085772821fb82c884467fb591f1959092a59/dxapp.json#L31)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

I've not used the suggestions tag before, does it auto fill a dropdown box?
</blockquote></details>

I think it's mostly for the UI, When browsing for the files at the bottom it suggests links to files so you don't have to search for them
___
*[src/code.sh, line 68 at r5](https://reviewable.io/reviews/moka-guys/dnanexus_ed_readcount_analysis/1#-Ms_qeKp2TWVs4qOlBLx:-Msb3E-11g0ItQbtppgU:bck5071) ([raw file](https://github.com/moka-guys/dnanexus_ed_readcount_analysis/blob/f06f085772821fb82c884467fb591f1959092a59/src/code.sh#L68)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

You don't need to use ls or trim, globbing will return an array of bams at that locate , this code is equivalent to:
</blockquote></details>

made changes

**Comment by Graeme-Smith** [comment]
:lgtm:

**Review by Graeme-Smith — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_ed_readcount_analysis/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @natashapinto)

**Pull request merged**
